export const regions = [
  { id: "north", name: "北部", subtitle: "学习与生活", x: 48, y: 13 },
  { id: "west", name: "西部", subtitle: "运动与漫游", x: 26, y: 47 },
  { id: "east", name: "东部", subtitle: "展览与艺术", x: 76, y: 42 },
  { id: "south", name: "南部", subtitle: "抵达与日常", x: 55, y: 79 },
];

export const places = [
  {
    id: "museum",
    name: "美术馆",
    type: "place",
    category: "展览",
    regionId: "east",
    x: 87,
    y: 40,
    tags: ["看展", "代表性", "第一次来", "打卡"],
    relations: { nearby: ["thinker", "history_museum"], contains: ["cafe", "charging"] },
    actions: ["view_detail", "add_to_route", "create_journal"],
    constraints: { requiresRegionUnlocked: true },
    metadata: {
      description: "校园里最重要的展览空间之一，也是理解央美创作现场的入口。",
      facilities: ["展览", "咖啡", "共享充电宝"],
      representativeScore: 0.98,
      visitMinutes: 8,
    },
  },
  {
    id: "thinker",
    name: "思考者",
    type: "landmark",
    category: "打卡",
    regionId: "west",
    x: 47,
    y: 39,
    tags: ["打卡", "代表性", "第一次来", "雕塑"],
    relations: { nearby: ["library", "museum"] },
    actions: ["view_detail", "add_to_route", "create_journal"],
    constraints: { requiresRegionUnlocked: true },
    metadata: {
      description: "在校园中心静静思考的经典雕塑，是许多人的央美第一印象。",
      facilities: ["拍照", "休息"],
      representativeScore: 0.94,
      visitMinutes: 5,
    },
  },
  {
    id: "library",
    name: "图书馆",
    type: "place",
    category: "建筑",
    regionId: "west",
    x: 38,
    y: 34,
    tags: ["建筑", "第一次来", "安静", "代表性"],
    relations: { nearby: ["thinker"] },
    actions: ["view_detail", "add_to_route"],
    constraints: { requiresRegionUnlocked: true },
    metadata: {
      description: "承载阅读与研究的校园建筑，也是一处适合慢下来观察的空间。",
      facilities: ["图书馆", "卫生间", "开水间"],
      representativeScore: 0.86,
      visitMinutes: 7,
    },
  },
  {
    id: "north_cafe",
    name: "北咖啡",
    type: "facility",
    category: "补给",
    regionId: "north",
    x: 77,
    y: 17,
    tags: ["补给", "咖啡", "充电"],
    relations: { inside: "north_hall" },
    actions: ["view_detail", "add_to_route"],
    constraints: { requiresRegionUnlocked: true },
    metadata: {
      description: "穿行北区时可以短暂停留的补给点。",
      facilities: ["咖啡", "共享充电宝"],
      representativeScore: 0.45,
      visitMinutes: 6,
    },
  },
  {
    id: "south_gate",
    name: "南门",
    type: "entrance",
    category: "出入口",
    regionId: "south",
    x: 49,
    y: 96,
    tags: ["第一次来", "入口", "代表性"],
    relations: { connects: ["outside", "south"] },
    actions: ["view_detail", "set_as_start"],
    constraints: { requiresRegionUnlocked: true },
    metadata: {
      description: "许多校园探索从这里开始。",
      facilities: ["出入口"],
      representativeScore: 0.72,
      visitMinutes: 2,
    },
  },
  {
    id: "canteen",
    name: "第一食堂",
    type: "facility",
    category: "补给",
    regionId: "south",
    x: 56,
    y: 84,
    tags: ["补给", "吃饭", "日常"],
    relations: { nearby: ["south_gate"] },
    actions: ["view_detail", "add_to_route"],
    constraints: { requiresRegionUnlocked: true },
    metadata: {
      description: "探索途中补充能量，也能感受校园日常。",
      facilities: ["餐饮"],
      representativeScore: 0.5,
      visitMinutes: 12,
    },
  },
];
